### ISSUE TITLE
Image attributes dissapear if there is a class attribute 

### ISSUE THREAD

**Issue by s-kris** [JiHong88/SunEditor#1006]
If an image is pasted into the editor or img tag is pasted via html editor that contains a class attribute with any name except se-editor then all the attributes are cleared.

**To Reproduce**
1. Paste the following image tag in editor via html:  `<img class="random-abc" src="https://picsum.photos/500/300" data-id="test" />`.
2. Switch to wsiwyg mode.
3. The image will be broken.

You can see that the src and other attributes are cleared in html editor mode.

**Expected behavior**
Image should be retained

**Screenshots**

before:
![Screenshot 2022-05-19 at 1 46 48 AM](https://user-images.githubusercontent.com/3975305/169148745-40f61262-c218-4bc9-ad1e-ced204930e58.png)

after:
![Screenshot 2022-05-19 at 1 46 59 AM](https://user-images.githubusercontent.com/3975305/169148797-495ebe9e-c7f2-45eb-a102-1050e1b33de9.png)

Additional context:

This is similar to https://github.com/JiHong88/SunEditor/issues/926

**Comment by JiHong88** [comment]
This issue is not reproduced.
Please tell me more detail of the test environment

<img width="588" alt="스크린샷 2022-05-19 오후 8 42 47" src="https://user-images.githubusercontent.com/13191953/169285778-1b6f616b-d1b1-43de-9060-1aa49f7ea8c6.png">

<img width="595" alt="스크린샷 2022-05-19 오후 8 42 56" src="https://user-images.githubusercontent.com/13191953/169285748-a9c0a066-9101-4866-850a-0aa3218536f9.png">

**Comment by s-kris** [comment]
This was happening with `suneditor-react: 2.16.0` ( it is based on`suneditor: 2.36.5`).

I upgraded to the latest version of both. The bug is gone.
Thank you!
