### ISSUE TITLE
Don't F**k with HTML option

### ISSUE THREAD

**Issue by bobwoofix** [JiHong88/suneditor#1320]
Seriously, there should be a 'Don't F**k with My HTML' option. I don't understand why so much of the HTML is being changed, deleted or wrapped with some custom tags.

**Comment by melloware** [comment]
We have incorporated SunEditor in PrimeFaces Extensions and missing this ability to not touch the HTML is the biggest complaint  have gotten so far about SunEditor: https://www.primefaces.org/showcase-ext/sections/sunEditor/basicUsage.jsf

**Comment by rider87** [comment]
Any plans here? Without such option this Editor is completely useless.

**Comment by JiHong88** [comment]
It is designed that way to process formats such as images and tables.
If everything is done in free form, it is difficult to select or edit images or etc.
This is my lack of skill.
In version 3.0.0, I modifying it so that users can select it step by step.

Before updating to version 3.0.0, I will add 'strictMode' to the next version to prevent HTML clean-related tasks.

And you can temporarily disable it as follows:
```javascript
editorInstance.core.cleanHTML = function (html) {return html;}
editorInstance.core.convertContentsForEditor = function (html) {console.log(html);return html;}
```

**Comment by melloware** [comment]
awesome @JiHong88 !!!

**Comment by bobwoofix** [comment]
Thanks heaps for your help with this -- let me know if I can assist in some way.

BTW what version does these functions work on? -- and what do they do?

**Comment by JiHong88** [comment]
It is version 2.

Version 3 is currently under development and is almost complete.
https://github.com/JiHong88/suneditor/tree/version/3
