### ISSUE TITLE
Unify icon style

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#215]
I think all icons should look like those which are bolder.

![image](https://user-images.githubusercontent.com/1231703/74319446-427e9a00-4d7f-11ea-8971-3ae6a2b50101.png)

**Comment by MRB60** [comment]
Not imminent for me but I agree it would be nice to be able to customize the icons used, both for style but also for adding missing ones (e.g. for custom plugins). 
And it is. 
By modifying font and css folder under assets, you can generate any fonts/icons you want.
However, if they shall contribute to Suneditor, Unify icons are not the first choice since they are not under a "free" license. Icons under some other licence than Unify should be selected instead.
Here is a list of popular (mostly "free") icons to chose from:
https://1stwebdesigner.com/best-free-icon-fonts-web-design/

Perhaps a short instruction how to generate other icons (and fonts) could be prepared...

**Comment by JiHong88** [comment]
Hi, @natanielcz @MRB60 
The icons are svg merge file created from [https://glyphter.com/](https://glyphter.com/).
I wanted to match the border width of all the icons,
But, I can't found icons to replace the "Regular icons" :(

**Comment by MRB60** [comment]
@JiHong88 ,
What do you mean that you cannot find icons to replace regular icons?
Not even by https://materialdesignicons.com/ ?

**Comment by JiHong88** [comment]
@MRB60 
Sorry for the confusion.
That reply about comment of @natanielcz 

I didn't know a [materialdesignicons.com]( https://materialdesignicons.com/).
It looks good.
It may be better to use "[inline svg](https://dev.materialdesignicons.com/getting-started#inline-svg)" in the editor than web fonts. #206

**Comment by MRB60** [comment]
Ok,
I agree that inline svg fonts/icons is probably more efficient for core and basic plugins.
However, it would be nice to find a generic solution for future plugins (and custom plugins) where new icons would be needed - either by extending existing font/icons used "inline" (thus an instruction how to extend) or allowing to include fonts/icons as web font.

**Comment by JiHong88** [comment]
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
