### ISSUE TITLE
fullPage does not work

### ISSUE THREAD

**Issue by dramalcolm** [JiHong88/SunEditor#240]
An error occur [SUNEDITOR.constructor.iframe.fail] The suneditor CSS files installation path could not be automatically detected. Please set the option property "iframeCSSFileName" before creating editor instances.

**Comment by JiHong88** [comment]
Hi, @dramalcolm 

When use the `fullPage` or `iframe` option.
Editor is find the css file to load inside the iframe.
Unless otherwise specified in the `iframeCSSFileName` option, finds a css file named "suneditor".
Define the `iframeCSSFileName` option. [options](https://github.com/JiHong88/SunEditor#options)
