### ISSUE TITLE
Turn off focus on setContents

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#246]
Hi,

I've seen that you've closed ticket #218, but unfortunately the issue still exists. Please take a look at the demo here: https://mrwl6.csb.app/ (source here: https://codesandbox.io/s/suneditor-autofocus-mrwl6). I'm focusing the second editor and then setting contents of first editor. I assume, that second editor shouldn't set focus to itself, but it does.

Cheers!

**Comment by JiHong88** [comment]
Hi,

I checked the code again.
It is a difficult work. 😔
The editor update the `history` stack after call `setContents`.
In this process, the cursor position of the editor is saved.
However, since the editor has never had focus, there is no `range` object of the pre-stored editor, so after setting the focus in the editor, the `range` object is returned.

Please use `editor.core.context.element.wysiwyg.blur()`
And if you are using the `setContents` method to set the initial value call [history.reset](http://suneditor.com/sample/html/out/document-editor.html#history).

Thank you 🙏

**Comment by JiHong88** [comment]
Hi again

Sorry for the confusion.
Fixed to give initial value when there is no `range` object.
Applies to the next version.

Thank you.

**Comment by JiHong88** [comment]
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
