### ISSUE TITLE
onload and setContents

### ISSUE THREAD

**Issue by mkhstar** [JiHong88/SunEditor#446]
Hi @JiHong88,
In the latest release of suneditor, the onload function is never been called and the setContents is been set without inserting in the onload function. Please can you check on this

**Comment by JiHong88** [comment]
Hi @mkhstar :)

In previous versions, it was called in the "setTimeout" function and an error occurred when called before "onload".
But it changed.

`onload` is call in the [_editorInit](https://github.com/JiHong88/SunEditor/blob/master/src/lib/core.js#L4901).
`_editorInit` method is called elsewhere depending on whether or not "iframe" is used.

iframe:
```javascript
contextEl.wysiwygFrame.addEventListener('load', function () {
  util._setIframeDocument(this, options);
  core._editorInit(false, options.value);
  options.value = null;
});
```
not using iframe:
```javascript
core._editorInit(false, options.value);
options.value = null;
```

So if you don't use "iframe", you can use "setContents" right away, but it won't work when you use the "iframe" option.
**Using the "setContents" function before "onload" is not the right way.**
Because due to the nature of the web, this code can also reuse "setTimeout".

**Comment by mkhstar** [comment]
The problem is in the latest version, editor.onload is never called. Please can you check that

**Comment by JiHong88** [comment]
I will release new version at today

**Comment by JiHong88** [comment]
@mkhstar The [2.32.1](https://github.com/JiHong88/SunEditor/releases/tag/2.32.1) version has been updated.
Thank you!
