### ISSUE TITLE
SunEditor didn't working at Vue-Cli when I import the Link or Image or Video.

### ISSUE THREAD

**Issue by lacuca** [JiHong88/SunEditor#62]
Vue에서 쓸려고 하니 Image 삽입할려고 버튼누르자마자 Error가 발생합니다.

### SunEditor.vue
```
<template lang="html">
  <textarea id="sample">Hi</textarea>
</template>

<script>
export default {
  mounted() {
    const suneditor = SUNEDITOR.create('sample',{
      width: '80%',
      height: '500px'
    });
  }
}
</script>

<style lang="css">
</style>
```

### Hello.vue
```
<template lang="html">
  <div>
    <p class="text-info">Hello.vue</p>
    <SunEditor></SunEditor>
  </div>
</template>

<script>
import SunEditor from './SunEditor.vue'

export default {
  components : {
    SunEditor
  }
}
</script>

<style lang="css">
</style>
```

### Erro Message in /src/suneditor.js
![image](https://user-images.githubusercontent.com/13599844/45588433-a533f200-b94f-11e8-8dd5-57b83b15eff8.png)

**Comment by rousos87** [comment]
@lacuca I think the problem is because it doesn't find the file of each plugin. Right now when you click the button it tries to find the plugin's file path, append the script file, and then call it. When it calls the plugin it doesn't find the path on node_modules folder. That's why you have this error. 
Right now the way is written does not play very well with the existing libraries and frameworks.

There is an second branch right now that will be more modular to be used by libraries, frameworks and bundlers.

It will be available soon.

Thanks

**Comment by JiHong88** [comment]
안녕하세요~

기존 버전은 노드 환경에서 제대로 동작하지 않습니다.

2.0.0 버전 부터 사용 가능합니다.

버전 업데이트를 했으니 다시 다운로드해서 사용해보세요.^^

예제 파일도 같이 업데이트 했습니다.
