### ISSUE TITLE
setContent removing data attributes

### ISSUE THREAD

**Issue by sdraper69** [JiHong88/SunEditor#866]
If I do something like...
`
editor.setContents('<p><span class="className" data-propA="A" data-propB="B">TEXT</span><br></p>');`

I get the p and the span and its class, but no data attributes.

![image](https://user-images.githubusercontent.com/25779335/131536420-7f65e191-c3ed-4acb-87ab-0b1fd6cf28d5.png)

Can you confirm if this is a bug or am I doing something wrong?
Thanks

**Comment by JiHong88** [comment]
@sdraper69 You must be define the "attributesWhitelist" option.
```
attributesWhitelist: {
 all: "data-propA|data-propB"
}
```

**Comment by sdraper69** [comment]
Great !! Sorry i missed that in the docs

**Comment by roker15** [comment]
> @sdraper69 You must be define the "attributesWhitelist" option.
> 
> ```
> attributesWhitelist: {
>  all: "data-propA|data-propB"
> }
> ```

Hi Your work is best out there --- after experimenting with every big and famous editor in last one month, Only your editor looks promising for my project ---- My project has big future prospect ---- so before i bet on it , help me in following aspect --- and be honest ---
**1.  Are you serious about your this editor? because i see less frequent update and most of discussion , issue are unresolved on git.**
**2. What are your future plan about this editor. Are you going to maintain and develop it seriously?**
**3.  Have you designed your editor for editing or rendering/publishing also? Can i render 100 Suneditor instance on a page for public user to read content? Do you recomment this? Or i need to just save html from Suneditor to database and then render it separately in some other component?**
**4. Although this is best editor i have seen, Why this is not getting more attention and starts?**

**Comment by JiHong88** [comment]
@roker15 Sorry, for the late reply.
1. Yeah sure, 
Previously, it was updated very frequently.
However, lately I've been too busy to have time to update the editor.
2. Future plan is to release [v3.0.0](https://github.com/JiHong88/SunEditor/projects/2) version.
As you can see from the previous commit history, I do my best to update.
3. Many instances can be rendered, but not recommended.
It will be improved to be able to render all in one instance in "3.0.0" version.
4. It still lacks in many areas.
You need to pay more attention to the design or the details.
