### ISSUE TITLE
Change event

### ISSUE THREAD

**Issue by redone80** [JiHong88/SunEditor#90]
Hi JiHong88,

Can you add onchange event for auto update content?
onKeyUp event only track when I type. But I click toolbar button it can not track.

**Comment by DeZZar** [comment]
Hi @redone80 ,

Due to the nature of WYSIWIG implementations you are not dealing with form fields which natively have an onChange event that can be used to monitor for change. This is a content editable page division therefore the keyUp event (fired after content is updated) is currently the best way to watch for change.  You would need to do something like fire the .getContents() function on the editor after each keyUp and compare it to the last saved contents to determine if change has occured - if you detect change then trigger the save event or any other event you want.

JiHong88 may have other advice to give.

DG

**Comment by JiHong88** [comment]
Hi @redone80 , @DeZZar  is right.

Due to the nature of the "contenteditable" implementation, the "onchange" event does not occur.

Instead, will be able to implement the "onChange" event by detecting the [history](http://suneditor.com/sample/html/out/document-editor.html#history) stack changes in the editor.

I will include it in the version to be updated today.

Thank you.

**Comment by redone80** [comment]
Hi @JiHong88,  @DeZZar.

Thank for updating.
I think onChange event is important. Sometimes we just only use mouse. So onKeyUp event does not fire.

**Comment by JiHong88** [comment]
Hi @redone80 ,

Yes, the onChange event is also important.

Added in [v2.14.0](https://github.com/JiHong88/SunEditor/releases/tag/2.14.0).

Thank you : )
