### ISSUE TITLE
modules needed for plugins

### ISSUE THREAD

**Issue by daybat** [JiHong88/SunEditor#956]
hi,
when we need to make a custom plugin we need modules like **dialog**, **anchor** etc.
The **suneditor.min.js** file itself contains built in predefined plugins and all the modules needed to work these plugins are already inside this file. Why should I reimport modules again for custom plugins? How can I use the build in modules from the **suneditor.min.js** file?

BTW, the **suneditor.min.js** file weight is 2.29MB (!!!) Is it OK?
![image](https://user-images.githubusercontent.com/47280571/158041699-dd62896f-72a8-4c85-96e3-1bbffadf9b3b.png)

**Comment by JiHong88** [comment]
This is because you don't know which plugin will register the module first.
In the current structure, the module is not registered and the module must be registered once.
Modules are registered in the plug-in, and already registered modules are not registered again.
The reason each plugin registers a module is that you don't know which plugin will use the module first.
This strange structure appears in 3.0.0

**Comment by JiHong88** [comment]
> you can not make the structure of your project like so called "user friendly". right?

Are you saying it's developer friendly?

> the size of suneditor.min.js can not be reduce. right?

Yes

**Comment by daybat** [comment]
**user** (the users of your product) means **developer** (a person who needs to extend the functionality of your product by his/her own needs).
People who write you messages here are the **first** users and they try to adopt your product to their final projects and to make it "user friendly" to final users or customers.

you can not make the structure of your project like so called "user (developer) friendly". right?

**Comment by JiHong88** [comment]
Yes, it is not easy to create custom plugins in the current structure.
I'm trying to improve in version 3.0.0.

**Comment by daybat** [comment]
ok. noted. thank you for answers
